spring:
  profiles:
    active: prod
# server
server:
  port: 8080
# spring 配置
spring:
  http:
    encoding:
      charset: utf-8
  aop:
    auto: true
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB